name: Release (Linux, macOS, Windows)
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'reason'
        required: false
  push:
    tags:
      - '*'
      - '!*-alpha*'

jobs:
  linux:
    name: Linux Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine Version
        run: |
          VERSION=$(git describe --tags)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.25.1'
      - name: Build Backend (amd64)
        run: |
          cd server
          go mod download
          go build -ldflags "-s -w -X '7x-api/common.Version=$VERSION' -extldflags '-static'" -o 7x-api-server-$VERSION
      - name: Build Backend (arm64)
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y gcc-aarch64-linux-gnu
          cd server
          CC=aarch64-linux-gnu-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -ldflags "-s -w -X '7x-api/common.Version=$VERSION' -extldflags '-static'" -o 7x-api-server-arm64-$VERSION
      - name: Generate checksums
        run: sha256sum server/7x-api-server-* > checksums-linux.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            server/7x-api-server-*
            checksums-linux.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    name: macOS Release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine Version
        run: |
          VERSION=$(git describe --tags)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.25.1'
      - name: Build Backend
        run: |
          cd server
          go mod download
          go build -ldflags "-X '7x-api/common.Version=$VERSION'" -o 7x-api-server-macos-$VERSION
      - name: Generate checksums
        run: shasum -a 256 server/7x-api-server-macos-* > checksums-macos.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            server/7x-api-server-macos-*
            checksums-macos.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    name: Windows Release
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine Version
        run: |
          VERSION=$(git describe --tags)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.25.1'
      - name: Build Backend
        run: |
          cd server
          go mod download
          go build -ldflags "-s -w -X '7x-api/common.Version=$VERSION'" -o 7x-api-server-$VERSION.exe
      - name: Generate checksums
        run: sha256sum server/7x-api-server-*.exe > checksums-windows.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            server/7x-api-server-*.exe
            checksums-windows.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}